implementation/agp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cultivo/",include("cultivo_main.urls")),
    # path("accounts/",include("users.urls")),
    # path("accounts/",include("django_registration.backends.activation.urls")),
    # path("accounts/",include("django.contrib.auth.urls")),
]

implementation/agp_main/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url
from django.views import generic


app_name="cultivo_main"    #called namespacing of urls,,,so as to distinguish between similar named urls 				#of different apps
urlpatterns=[
    path(r'',views.TemplateView.as_view(),name="home"),
    path(r'contact',views.TemplateView2.as_view(),name="contact"),
    path(r'story',views.TemplateView3.as_view(),name="story"),
    path(r'services',views.TemplateView4.as_view(),name="services"),
    # path(r'contactus',views.TemplateView_con.as_view(),name="contact"),

    path(r'result',views.work,name="result"),
    # path(r'form_signin',views.)
    # path('upload',views.upload,name="upload"),
]

implementation/agp_main/models.py
from django.db import models


class pred_one(models.Model):
    crop=models.CharField(max_length=15)
    Gross_Production_Value_constant_2004_2006_1000_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Net_Production_Value_constant_2004_2006_1000_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_current_million_SLC=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_constant_2004_2006_million_SLC=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_current_million_US_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_constant_2004_2006_million_US_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    org_mean_Gross_Production_Value_constant_2004_2006_million_US_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)

    def __str__(self):
    	return self.crop


class prod_area(models.Model):
    state=models.CharField(max_length=25)
    district=models.CharField(max_length=25)
    crop=models.CharField(max_length=25)
    org_val=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    pred_val=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)

    def __str__(self):
    	return '%s %s %s' % (self.state, self.district, self.crop)


class one(models.Model):
    crop=models.CharField(max_length=15)
    Gross_Production_Value_constant_2004_2006_1000_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Net_Production_Value_constant_2004_2006_1000_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_current_million_SLC=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_constant_2004_2006_million_SLC=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_current_million_US_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    Gross_Production_Value_constant_2004_2006_million_US_dollar=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)

    def __str__(self):
    	return self.crop


class two(models.Model):
    crop=models.CharField(max_length=25)
    area_harvested=models.IntegerField()
    yieldd=models.IntegerField()
    production=models.IntegerField()

    def __str__(self):
    	return self.crop


class three(models.Model):
    crop=models.CharField(max_length=15)
    Production=models.IntegerField()
    Imports=models.IntegerField()
    Stock=models.IntegerField()
    Export=models.IntegerField()
    Seed=models.IntegerField()
    Domestic=models.IntegerField()

    def __str__(self):
    	return self.crop


class pred_three(models.Model):
    crop=models.CharField(max_length=15)
    imports=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    exports=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    production=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    production_mean=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    imports_mean=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)
    exports_mean=models.DecimalField(max_digits=12,decimal_places=4,default=0.0)

    def __str__(self):
    	return self.crop

implementation/agp_main/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.views import generic
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from tablib import Dataset
from rapidconnect import RapidConnect    #to use a rapid api
import pprint       #pretty print a json
import requests     #access apis
import datetime     #get current date and time
import statistics   #calculate mean

count=0


# =======================================FOR WORK USING THE API OF WEATHER AND SOIL DETAILS=====================================


#to get the current temperature and weather information
def api_for_weather(place):
    
    result=requests.get('http://api.openweathermap.org/data/2.5/weather?q='+place+'&appid=26215a2614573c7ce3405f3338415d10')
    data=result.json()
    return data

def api_for_weather_2(lat,longi):
    
    result=requests.get('http://api.openweathermap.org/data/2.5/weather?lat='+str(lat)+'&lon='+str(longi)+'&appid=26215a2614573c7ce3405f3338415d10')
    data=result.json()
    return data


def calculate_coord(data):
        coord=[data['coord']['lat'],data['coord']['lon']]
        return coord


#to get the information about the soil of the region or district

def get_soil_info(place,coord):
    def api_for_geocon(place):
        now = datetime.datetime.now()
        start_date=str(now.year)+'-'+str(now.month-1)+'-'+str(now.day)
        end_date=str(now.year)+'-'+str(now.month+1)+'-'+str(now.day)
    #    result=requests.get('https://api.weatherbit.io/v2.0/history/agweather?lat='+str(coord[0])+'&lon='+str(coord[1])+'&start_date='+start_date+'&end_date='+end_date+'&key=283a77fe5cbe46718430e4d5418be6c1')
        result=requests.get('https://api.weatherbit.io/v2.0/forecast/agweather?lat='+str(coord[0])+'&lon='+str(coord[1])+'&key=3d6dc8552cb74208866db831e6cc7724')
        data=result.json()
        return data
    
    def cal_mean(data):
        mean_vals=[]
        summ_vals_dict={}
        keywords=['bulk_soil_density','skin_temp_avg','precip','specific_humidity','pres_avg','soilt_0_10cm','soilm_0_10cm','wind_10m_spd_avg']
        for k in keywords:
            summ=0
            for i in range(0,9):
                summ+=data['data'][i][k]
            summ_vals_dict[k]=summ
        for key in summ_vals_dict:
            summ_vals_dict[key]=(summ_vals_dict[key])/9
    
        return summ_vals_dict
    
    
    daaa=api_for_geocon(place)
    return cal_mean(daaa)

def geocoding(place):
    coord=[]
    result=requests.get('https://api.opencagedata.com/geocode/v1/json?q='+place+'&key=217e890a4fed4cc780a83c8cce2abf14')
    data=result.json()
    coord.append(data['results'][0]['geometry']['lat'])
    coord.append(data['results'][0]['geometry']['lng'])
    return (coord,data)

def print_temp_details(data):
       
       temp=precise((data['main']['temp']-273.15),1)
       wind=precise((data['wind']['speed']*1.60934),2)
       dire=precise((data['wind']['deg']),2)

       values={
               'temperature':str(temp),
               'latitude':str(data['coord']['lat']),
               'longitude':str(data['coord']['lon']),
               'humidity':str(data['main']['humidity'])+'%',
               'pressure':str(data['main']['pressure'])+'hPa',
               'windspeed':str(wind)+'km/h',
               'winddirection':str(dire)
            #    'visibility':str(data['visibility'])+' metres',
               }
       
       return values



def precise(data,point):
    if type(data)==dict:
        a={}
        for i in data:
            if type(data[i])==float:
                data[i]=round(data[i],point)
                a[i]=data[i]
            else:
                a[i]=data[i]
        return a
    if type(data)==float:
        return round(data,point)
    
    if type(data)==list:
        a=[]
        for i in data:
            if type(i)==float:
                i=round(i,point)
                print(i)
                a.append(i)
            else:
                a.append(i)
        return a


def categorize(val1,val2):
    if val1>val2:
        pp=(val2/val1)
        return pp
    else:
        return 1


def finding_subs(p,crop1):
    d={}
    for i in p.values():
        crop=i['crop']
        area=i['district']

        first_datset=pred_one.objects.filter(crop=crop)
        sec_datset=prod_area.objects.filter(crop=crop,district=area)
        third_datset=pred_three.objects.filter(crop=crop)
        
        if first_datset.count()!=0 and sec_datset.count()!=0 and third_datset.count()!=0:

            sec_val=list(sec_datset.values())[0] 
            val1=sec_val['org_val']
            val2=sec_val['pred_val']

            p1=categorize(val1,val2)

    #handing the  Gross_Production_Value_current_million_US_dollar factor
            
            fir1=list(first_datset.values())[0]['Gross_Production_Value_constant_2004_2006_million_US_dollar']
            fir2=list(first_datset.values())[0]['org_mean_Gross_Production_Value_constant_2004_2006_million_US_dollar']

            p2=categorize(fir1,fir2)
            
    # handling the imports exports and production factors
            firr1=list(third_datset.values())[0]

            val1_1=firr1['exports']
            val2_2=firr1['imports']
            val3_3=firr1['production']

            val1_1_p=firr1['exports_mean']
            val2_2_p=firr1['imports_mean']
            val3_3_p=firr1['production_mean']

            p3=categorize(val1_1,val1_1_p)
            p4=categorize(val2_2,val2_2_p)
            p5=categorize(val3_3,val3_3_p)

            mean_final=(p1+p2+p3+p4+p5)/5

            d[crop]=mean_final
    
    else:
        d[crop]='no db exist for the crop'

    
    e={}
    for i in d:
        if type(d[i])!=str and i!=crop1:
            e[i]=d[i]
    return e


# ==========================================MAIN DJANGO VIEWS=============================================



class TemplateView(generic.TemplateView):
    template_name='cultivo_main/footer.html'

class TemplateView2(generic.TemplateView):
    template_name='cultivo_main/contact.html'

class TemplateView3(generic.TemplateView):
    template_name='cultivo_main/story.html'

class TemplateView4(generic.TemplateView):
    template_name='cultivo_main/services.html'


def work(request):
    if request.method=='POST':
        area=request.POST['area'].upper()
        crop=request.POST['crop'].capitalize()

        if (prod_area.objects.filter(crop=crop,district=area)).count()>=1:
            #getting the atmosphere information
            data=api_for_weather(area)                  #getting the json details of the atmosphere
            if 'cod' in data and data['cod']=='404':
                coord,data=geocoding(area)
                if data['status']['code']==200 and data['status']['message']=='OK':
                    data=api_for_weather_2(coord[0],coord[1])
                else:
                    return render(request,'cultivo_main/error.html')
            
            
            coord=calculate_coord(data)                 #extracting the coordinates
            soil_info=get_soil_info(area,coord)         #dictionary cointaining soil info
            temp_det=print_temp_details(data)       #converting all the details into proper units for printing

            soil_info=precise(soil_info,2)
            # temp_det_2=precise(temp_det,1)

            # filtering the objects

            first_datset=pred_one.objects.filter(crop=crop)
            sec_datset=prod_area.objects.filter(crop=crop,district=area)
            third_datset=pred_three.objects.filter(crop=crop)


            # #gettting dictionaries out of the returned values

            fir=list(first_datset.values())[0]['Gross_Production_Value_constant_2004_2006_million_US_dollar']
            first_value={'Gross_Production_Value_constant_2004_2006_million_US_dollar':round(fir,2)}


            sec_values=list(sec_datset.values())[0]
            del sec_values['id']
            del sec_values['org_val']

            third_values=list(third_datset.values())[0]
            del third_values['id']
            del third_values['crop']


            final_dict={**sec_values,**third_values,**first_value}
            
            # finding the final % success and failure

    # handling prod_area factor
            sec_val=list(sec_datset.values())[0] 
            val1=sec_val['org_val']
            val2=sec_val['pred_val']

            p1=categorize(val1,val2)

    #handing the  Gross_Production_Value_current_million_US_dollar factor
            
            fir1=list(first_datset.values())[0]['Gross_Production_Value_constant_2004_2006_million_US_dollar']
            fir2=list(first_datset.values())[0]['org_mean_Gross_Production_Value_constant_2004_2006_million_US_dollar']

            p2=categorize(fir1,fir2)
            
    # handling the imports exports and production factors
            firr1=list(third_datset.values())[0]

            val1_1=firr1['exports']
            val2_2=firr1['imports']
            val3_3=firr1['production']

            val1_1_p=firr1['exports_mean']
            val2_2_p=firr1['imports_mean']
            val3_3_p=firr1['production_mean']

            p3=categorize(val1_1,val1_1_p)
            p4=categorize(val2_2,val2_2_p)
            p5=categorize(val3_3,val3_3_p)

            mean_final=(p1+p2+p3+p4+p5)/5

            # final_outcome=mean_final
            # final_outcome=round(mean_final,)
            final_outcome=(round(mean_final,5))*100
            final_outcome = float("{0:.3f}".format(final_outcome))
            final_main=str(final_outcome).split('.')[0]
            final_dec=str(final_outcome).split('.')[1]


            obj=prod_area.objects.filter(district=area)
            d=finding_subs(obj,crop) 
            dd=list(d[i] for i in d)
            dd=list(map(float,dd))
            dd.sort(reverse=True)
            fin_dict={}

implementation/agp_main/templates/agp_main/contact.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Cultivo</title>
    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <!-- GSAP -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"></script>
    <!--FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    </head>

    <style>
    html, body {
  margin:0;
  padding:0;
  width:100%;
  height:100vh;
  font-family: "Playfair Display";
  font-weight:lighter;
}
body {
   background: url(https://hdqwalls.com/wallpapers/sunset-fields-wide.jpg) no-repeat 50% 50%;   background-size:cover;
  
}
#name
{
  position:absolute;
  top:7%;
  left:10%;
  transform:translate(-50%, -50%);
  color:white;
  font-size:48px;
  font-family: "Playfair Display";
  font-weight:lighter;
}
h3
{
  position:absolute;
  top:90%;
  left:50%;
  transform:translate(-50%, -50%);
  color:#fff;
  font-size:18px;
  font-family: "Playfair Display";
  font-weight:lighter;
}

a {
  text-decoration:none;
  color:#fff;
}
*,:after,:before{box-sizing:border-box}
        .clearfix:after,.clearfix:before{content:'';display:table}
        .clearfix:after{clear:both;display:block}
        a{color:inherit;text-decoration:none}
        
        .login-wrap{
          top:25%;
          
            width:100%;
            margin:auto;
            max-width:835px;
            min-height:180px;
            position:relative;
            box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
        }
        .login-html{
            width:100%;
            height:100%;
            position:absolute;
            padding:40px 70px 20px 70px;
            background:#6D2600;
            opacity:.77;
            outlinr:none !important;
        }
        .login-html .sign-in-htm,
        .login-html .sign-up-htm{
            top:0;
            left:0;
            right:0;
            bottom:0;
            position:absolute;
            /* transform:rotateY(180deg); */
            /* backface-visibility:hidden; */
            /* transition:all .4s linear; */
        }
        .login-html .sign-in,
        .login-html .sign-up,
        .login-form .group .check{
            display:none;
        }
        .login-html .tab,
        .login-form .group .label,
        .login-form .group .button{
            text-transform:uppercase;
        }
        .login-html .tab{
            font-size:27px;
            margin-right:15px;
            padding-bottom:5px;
            margin:0 15px 10px 0;
            display:inline-block;
            border-bottom:2px solid transparent;
        }
        .login-html .sign-in:checked + .tab,
        .login-html .sign-up:checked + .tab{
            color:#fff;
            border-color:#2c420b;
        }
        .login-form{
            min-height:345px;
            position:relative;
            perspective:1000px;
            transform-style:preserve-3d;
        }
        .login-form .group{
            margin-bottom:15px;
        }
        .login-form .group .label,
        .login-form .group .input,
        .login-form .group .button{
            width:100%;
            color:#fff;
            display:block;
            outline:none !important;  
        }
        .login-form .group .input,
        .login-form .group .button{
            border:none;
            padding:15px 20px;
            border-radius:25px;
            background:rgba(255,255,255,.1);
        }
        .login-form .group input[data-type="password"]{
            text-security:circle;
            -webkit-text-security:circle;
        }
        .login-form .group .label{
            color:white;
            font-size:20px;
        }
        .login-form .group .button{
            background:#2c420b;
        }
        .login-form .group label .icon{
            width:15px;
            height:15px;
            border-radius:2px;
            position:relative;
            display:inline-block;
            background:rgba(255,255,255,.1);
        }
        .login-form .group label .icon:before,
        .login-form .group label .icon:after{
            content:'';
            width:10px;
            height:2px;
            background:#fff;
            position:absolute;
            transition:all .2s ease-in-out 0s;
        }
        .login-form .group label .icon:before{
            left:3px;
            width:5px;
            bottom:6px;
            transform:scale(0) rotate(0);
        }
        .login-form .group label .icon:after{
            top:6px;
            right:0;
            transform:scale(0) rotate(0);
        }
        .login-form .group .check:checked + label{
            color:#fff;
        }
        .login-form .group .check:checked + label .icon{
            background:#2c420b;
        }
        .login-form .group .check:checked + label .icon:before{
            transform:scale(1) rotate(45deg);
        }
        .login-form .group .check:checked + label .icon:after{
            transform:scale(1) rotate(-45deg);
        }
        .login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
            transform:rotate(0);
        }
        .login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
            transform:rotate(0);
        }
        
        .hr{
            height:3px;
            
            background:rgba(255,255,255,.2);
        }
        .foot-lnk{
            text-align:center;
        }

#container222
{
  position:absolute;
  top:35%;
  left:19%;

  color:white;
  font-size:30px;
  font-family: "Playfair Display";
  font-weight:lighter;
}


#link_another
{
    color:white;
    font-size:12px;
    margin-top:20px;
    font-family: "Playfair Display";
  font-weight:lighter;
}

</style>
  <body>    
      
    <div id="name"><a href={% url 'cultivo_main:home'%}>Cultivo</a></div>
    


<div class="login-wrap">
    <div class="login-html">
        <!-- <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label> -->
        <div class="login-form">
                <div class='group'>
                    <p class='label' align='center'>Feel free to contact us at @<br> aman.parmar17@gmail.com</p>
                </div>
            <div class="hr"  style='margin-top:-1%;'></div>
            <!-- <div id='link_another' align='center'><a href="{% url 'cultivo_main:home'%}"><u>Would you like to change your mind?</u></a></div>
                --> 
        

        
            </div>
            </div></div>










      
      <h3>&copy All rights reserved 2018-2019</h3>


  </body>
</html>

implementation/agp_main/templates/agp_main/import.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

implementation/agp_main/templates/agp_main/main_head.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Cultivo</title>
    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <!-- GSAP -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"></script>
    <!--FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    </head>

    <style>
    html, body {
  margin:0;
  padding:0;
  width:100%;
  height:100vh;
  font-family: "Playfair Display";
  font-weight:lighter;
}
body {
   background: url(https://hdqwalls.com/wallpapers/sunset-fields-wide.jpg) no-repeat 50% 50%;   background-size:cover;
  
}
#name
{
  position:absolute;
  top:7%;
  left:10%;
  transform:translate(-50%, -50%);
  color:white;
  font-size:48px;
  font-family: "Playfair Display";
  font-weight:lighter;
}
h3
{
  position:absolute;
  top:90%;
  left:50%;
  transform:translate(-50%, -50%);
  color:#fff;
  font-size:18px;
  font-family: "Playfair Display";
  font-weight:lighter;
}
.toggle-btn {
  position:fixed;
  margin:1.4em;
  margin-right:3em; 
  padding:1em;
  width:40px;
  height:12px;
  right:0;
  z-index:1;    
}
span.one {
  position:absolute;
  width:40px;
  height:2px;
  background:#fff;
}
span.two {
  position:absolute;
  width:40px;
  height:2px;
  background:#fff;
  margin-top:12px;
}
.menu {
  z-index:0;
  position:absolute;
  background:linear-gradient(#293302,#293302);
  opacity: .75;
  height:100vh;
  width:100%;
  top:-100%;
}
.data {
  padding: 8em 0 0 2em;
  text-align:left;
}
ul{
  list-style:none;
}
li:first-child {
  color:grey;
  font-family:Poppins;
  font-size:24px;
}
li:not(:first-child) {
  color:#fff;
  font-size:42px;
}
a {
  text-decoration:none;
  color:#fff;
}
*,:after,:before{box-sizing:border-box}
        .clearfix:after,.clearfix:before{content:'';display:table}
        .clearfix:after{clear:both;display:block}
        a{color:inherit;text-decoration:none}
        
        .login-wrap{
          top:20%;
          
            width:100%;
            margin:auto;
            max-width:525px;
            min-height:370px;
            position:relative;
            box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
        }
        .login-html{
            width:100%;
            height:100%;
            position:absolute;
            padding:40px 70px 20px 70px;
            background:#6D2600;
            opacity:.77;
            outlinr:none !important;
        }
        .login-html .sign-in-htm,
        .login-html .sign-up-htm{
            top:0;
            left:0;
            right:0;
            bottom:0;
            position:absolute;
            /* transform:rotateY(180deg); */
            /* backface-visibility:hidden; */
            /* transition:all .4s linear; */
        }
        .login-html .sign-in,
        .login-html .sign-up,
        .login-form .group .check{
            display:none;
        }
        .login-html .tab,
        .login-form .group .label,
        .login-form .group .button{
            text-transform:uppercase;
        }
        .login-html .tab{
            font-size:27px;
            margin-right:15px;
            padding-bottom:5px;
            margin:0 15px 10px 0;
            display:inline-block;
            border-bottom:2px solid transparent;
        }
        .login-html .sign-in:checked + .tab,
        .login-html .sign-up:checked + .tab{
            color:#fff;
            border-color:#2c420b;
        }
        .login-form{
            min-height:345px;
            position:relative;
            perspective:1000px;
            transform-style:preserve-3d;
        }
        .login-form .group{
            margin-bottom:15px;
        }
        .login-form .group .label,
        .login-form .group .input,
        .login-form .group .button{
            width:100%;
            color:#fff;
            display:block;
            outline:none !important;  
        }
        .login-form .group .input,
        .login-form .group .button{
            border:none;
            padding:15px 20px;
            border-radius:25px;
            background:rgba(255,255,255,.1);
        }
        .login-form .group input[data-type="password"]{
            text-security:circle;
            -webkit-text-security:circle;
        }
        .login-form .group .label{
            color:white;
            font-size:15px;
        }
        .login-form .group .button{
            background:#2c420b;
        }
        .login-form .group label .icon{
            width:15px;
            height:15px;
            border-radius:2px;
            position:relative;
            display:inline-block;
            background:rgba(255,255,255,.1);
        }
        .login-form .group label .icon:before,
        .login-form .group label .icon:after{
            content:'';
            width:10px;
            height:2px;
            background:#fff;
            position:absolute;
            transition:all .2s ease-in-out 0s;
        }
        .login-form .group label .icon:before{
            left:3px;
            width:5px;
            bottom:6px;
            transform:scale(0) rotate(0);
        }
        .login-form .group label .icon:after{
            top:6px;
            right:0;
            transform:scale(0) rotate(0);
        }
        .login-form .group .check:checked + label{
            color:#fff;
        }
        .login-form .group .check:checked + label .icon{
            background:#2c420b;
        }
        .login-form .group .check:checked + label .icon:before{
            transform:scale(1) rotate(45deg);
        }
        .login-form .group .check:checked + label .icon:after{
            transform:scale(1) rotate(-45deg);
        }
        .login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
            transform:rotate(0);
        }
        .login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
            transform:rotate(0);
        }
        
        .hr{
            height:2px;
            margin:60px 0 50px 0;
            background:rgba(255,255,255,.2);
        }
        .foot-lnk{
            text-align:center;
        }
</style>
  <body>    
      
    <div id="name"><a href='#'>Cultivo</a></div>
    <div class="toggle-btn">
      <span class="one"></span>
      <span class="two"></span>
    </div>
    
    <div class="menu">
      <div class="data">
        <ul>
          <li>Navigation</li>
          <li><a href="{% url 'cultivo_main:home'%}">Home</a></li>
          <li><a href="{% url 'cultivo_main:story'%}">Our Story</a></li>
          <li><a href="{% url 'cultivo_main:services'%}">Services</a></li>
          <li><a href="{% url 'cultivo_main:contact'%}">Contact</a></li>
         </ul>
       </div>
      </div>
{% block content %}{% endblock %}

      <script>
      var t1 = new TimelineMax({paused: true});
      
      t1.to(".one", 0.8, {
        y: 6,
        rotation: 45,
        ease: Expo.easeInOut
      });
      
      t1.to(".two", 0.8, {
        y: -6,
        rotation: -45, 
        ease: Expo.easeInOut,
        delay: -0.8
      });
      t1.to(".menu", .8,{
        top: "0%",
        ease: Expo.easeInOut,
        delay: -.6
      }); 
	  
      t1.staggerFrom(".menu ul li", 2, {x: -200, opacity: 0, ease: Expo.easeOut}, 0.1);
      
      t1.reverse();
      $(document).on("click", ".toggle-btn",function(){
        t1.reversed(!t1.reversed());
      });
t1.reverse();
      $(document).on("click", "a",function(){
        t1.reversed(!t1.reversed());
      });</script>

      
      
       <h3>&copy All rights reserved 2018-2019</h3> 

  </body>
</html>